[workspace]
channels = ["conda-forge"]
name = "r_llm"
platforms = ["osx-arm64","linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
r = ">=4.5,<4.6"
imagemagick = ">=7.1.2_9,<8"
libcurl = ">=8.17.0,<9"
